package client

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"

	dash0 "github.com/dash0hq/dash0-api-client-go"
)

func (c *dash0Client) CreateNotificationChannel(ctx context.Context, origin string, channelJSON string) error {
	def, err := unmarshalNotificationChannel(channelJSON)
	if err != nil {
		return fmt.Errorf("error parsing notification channel JSON: %w", err)
	}

	dash0.SetNotificationChannelOrigin(def, origin)

	tflog.Debug(ctx, fmt.Sprintf("Creating notification channel with origin: %s", origin))

	_, err = c.inner.UpdateNotificationChannel(ctx, origin, def)
	if err != nil {
		return err
	}

	tflog.Debug(ctx, fmt.Sprintf("Notification channel created with origin: %s", origin))
	return nil
}

func (c *dash0Client) GetNotificationChannel(ctx context.Context, origin string) (string, error) {
	def, err := c.inner.GetNotificationChannel(ctx, origin)
	if err != nil {
		return "", err
	}

	tflog.Debug(ctx, fmt.Sprintf("Notification channel retrieved with origin: %s", origin))
	return marshalToJSON(def)
}

func (c *dash0Client) UpdateNotificationChannel(ctx context.Context, origin string, channelJSON string) error {
	def, err := unmarshalNotificationChannel(channelJSON)
	if err != nil {
		return fmt.Errorf("error parsing notification channel JSON: %w", err)
	}

	dash0.SetNotificationChannelOrigin(def, origin)

	_, err = c.inner.UpdateNotificationChannel(ctx, origin, def)
	if err != nil {
		return err
	}

	tflog.Debug(ctx, fmt.Sprintf("Notification channel updated with origin: %s", origin))
	return nil
}

func (c *dash0Client) DeleteNotificationChannel(ctx context.Context, origin string) error {
	err := c.inner.DeleteNotificationChannel(ctx, origin)
	if err != nil {
		return err
	}

	tflog.Debug(ctx, fmt.Sprintf("Notification channel deleted with origin: %s", origin))
	return nil
}

// GetNotificationChannelMetadata resolves the server-assigned id and the web
// app deep-link URL for the notification channel with the given origin in a
// single GET request.
//
// The id is distinct from the origin: the origin (e.g. "tf_<uuid>") is the
// upsert key the provider controls, while the id is the bare dash0.com/id UUID
// generated by the server on creation and is the value other resources
// reference in their notification settings.
//
// Notification channels are organization-level (not dataset-scoped), so the
// resulting URL has no dataset query parameter. Both values are best-effort: an
// empty string is returned (with no error) when the channel has no id label (in
// which case the URL cannot be derived either), so callers can treat them as
// metadata rather than failing the operation.
func (c *dash0Client) GetNotificationChannelMetadata(ctx context.Context, origin string) (string, string, error) {
	def, err := c.inner.GetNotificationChannel(ctx, origin)
	if err != nil {
		return "", "", err
	}

	id := dash0.GetNotificationChannelID(def)
	if id == "" {
		tflog.Warn(ctx, fmt.Sprintf("Notification channel with origin %q has no id label; id and URL will be empty", origin))
		return "", "", nil
	}

	channelURL := dash0.DeeplinkURL(c.apiURL, dash0.DeeplinkAssetTypeNotificationChannel, id, nil)
	logResolvedURL(ctx, "notification channel", origin, channelURL)
	tflog.Debug(ctx, fmt.Sprintf("Resolved notification channel id %q for origin %q", id, origin))
	return id, channelURL, nil
}

// unmarshalNotificationChannel parses a JSON string into a NotificationChannelDefinition.
func unmarshalNotificationChannel(jsonStr string) (*dash0.NotificationChannelDefinition, error) {
	var def dash0.NotificationChannelDefinition
	if err := json.Unmarshal([]byte(jsonStr), &def); err != nil {
		return nil, err
	}
	return &def, nil
}
