package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"github.com/dash0hq/terraform-provider-dash0/internal/converter"
	"github.com/dash0hq/terraform-provider-dash0/internal/provider/client"
	customplanmodifier "github.com/dash0hq/terraform-provider-dash0/internal/provider/planmodifier"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"gopkg.in/yaml.v3"
)

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &CheckRuleResource{}
	_ resource.ResourceWithConfigure   = &CheckRuleResource{}
	_ resource.ResourceWithImportState = &CheckRuleResource{}
)

// NewCheckRuleResource is a helper function to simplify the provider implementation.
func NewCheckRuleResource() resource.Resource {
	return &CheckRuleResource{}
}

// CheckRuleResource is the resource implementation.
type CheckRuleResource struct {
	client client.Client
}

// checkRuleModel is the Terraform state model for a check rule resource.
type checkRuleModel struct {
	Origin        types.String `tfsdk:"origin"`
	ID            types.String `tfsdk:"id"`
	Dataset       types.String `tfsdk:"dataset"`
	CheckRuleYaml types.String `tfsdk:"check_rule_yaml"`
	URL           types.String `tfsdk:"url"`
}

// Configure adds the provider configured client to the resource.
func (r *CheckRuleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *CheckRuleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_check_rule"
}

func (r *CheckRuleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: `Manages a Dash0 Check Rule. Check rules define alerting conditions based on PromQL expressions that are continuously evaluated against your telemetry data. See [About Alerting](https://dash0.com/docs/dash0/monitoring/alerting/alerting) and [About Creating Check Rules](https://dash0.com/docs/dash0/monitoring/alerting/create-check-rules) for more details. The check rule definition uses the [Prometheus Rule format](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/).

More information on how Prometheus rules are mapped to Dash0 check rules can be found in the [Dash0 Operator documentation](https://dash0.com/docs/dash0/monitoring/kubernetes/about-kubernetes#managing-dash0-check-rules).`,

		Attributes: map[string]schema.Attribute{
			"origin": schema.StringAttribute{
				Description: "A unique identifier for the check rule, automatically generated on creation. Used to reference the check rule for updates, reads, deletes, and imports.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Description: "The server-assigned identifier of the check rule, resolved by the provider after creation. The Dash0 check-rules API addresses rules by their origin, so for this resource `id` equals `origin` (the `tf_`-prefixed value generated by the provider) — unlike dashboards, views, synthetic checks, and notification channels, where `id` is a distinct server-assigned UUID. The attribute is exposed for symmetry across resources; reference it when wiring the check rule's identifier into another resource.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"dataset": schema.StringAttribute{
				Description: "The identifier of the [Dash0 dataset](https://dash0.com/docs/dash0/miscellaneous/glossary/datasets) that the check rule belongs to. Provide the dataset's identifier, which is immutable, not the 'name'. Datasets are used to separate observability data within a Dash0 organization. Changing this value forces the resource to be recreated.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"check_rule_yaml": schema.StringAttribute{
				Description: "The check rule definition in YAML format, following the [Prometheus alerting rule specification](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/). The `dash0.com/sharing` metadata annotation is supported to control sharing settings; changes to it trigger a resource update. All other metadata annotations are managed by the server and ignored during drift detection.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					customplanmodifier.YAMLSemanticEqual(converter.AnnotationSharing),
				},
			},
			"url": schema.StringAttribute{
				Description: "The URL to open this check rule in the Dash0 web app, derived from the Dash0 API URL and the check rule's server-assigned identifier. Computed by the provider after creation. May be empty if the app URL cannot be derived (e.g. for self-hosted deployments with a custom web app domain).",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

// resolveCheckRule populates the check rule's server-assigned id and web app
// URL on the model by looking them up via the list endpoint. Both are
// best-effort metadata: failures are surfaced as warnings and leave the
// attributes null rather than failing the operation.
func (r *CheckRuleResource) resolveCheckRule(ctx context.Context, model *checkRuleModel, diags *diag.Diagnostics) {
	id, checkRuleURL, err := r.client.ResolveCheckRule(ctx, model.Origin.ValueString(), model.Dataset.ValueString())
	if err != nil {
		diags.AddWarning(
			"Unable to resolve check rule metadata",
			fmt.Sprintf("The check rule was saved successfully, but its id and URL could not be determined: %s", err),
		)
		model.ID = types.StringNull()
		model.URL = types.StringNull()
		return
	}
	if id == "" {
		model.ID = types.StringNull()
	} else {
		model.ID = types.StringValue(id)
	}
	if checkRuleURL == "" {
		model.URL = types.StringNull()
	} else {
		model.URL = types.StringValue(checkRuleURL)
	}
}

func (r *CheckRuleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model checkRuleModel
	diags := req.Plan.Get(ctx, &model)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	model.Origin = types.StringValue("tf_" + uuid.New().String())

	// Validate YAML format
	var checkRuleYaml interface{}
	err := yaml.Unmarshal([]byte(model.CheckRuleYaml.ValueString()), &checkRuleYaml)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid YAML",
			fmt.Sprintf("Check rule definition is not valid YAML: %s", err),
		)
		return
	}

	// Pass YAML directly to client (the client handles Prometheus->Dash0 conversion)
	err = r.client.CreateCheckRule(ctx, model.Origin.ValueString(), model.CheckRuleYaml.ValueString(), model.Dataset.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create check rule, got error: %s", err))
		return
	}

	// Resolve the id and web app URL for the newly created check rule (best-effort).
	r.resolveCheckRule(ctx, &model, &resp.Diagnostics)

	tflog.Trace(ctx, "created a check rule resource")

	// Set state to fully populated data
	diags = resp.State.Set(ctx, model)
	resp.Diagnostics.Append(diags...)
}

func (r *CheckRuleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state
	var state checkRuleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The client returns a Prometheus YAML string (Dash0->Prometheus conversion is done internally)
	apiResponseYAML, err := r.client.GetCheckRule(ctx, state.Origin.ValueString(), state.Dataset.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read check rule, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "read a check rule resource")

	// TODO Clean this up when we switch to the CRD-native API for check rules
	//
	// The Dash0 API does not preserve metadata.name for check rules (the
	// PrometheusAlertRule format lacks that field). Inject the name from
	// state into the API response so drift detection can compare properly.
	apiResponseYAML = injectMetadataName(state.CheckRuleYaml.ValueString(), apiResponseYAML)

	// Compare the current state with the retrieved check rule
	if state.CheckRuleYaml.ValueString() != "" {
		stateYAML := state.CheckRuleYaml.ValueString()
		additionalIgnored := converter.FieldsAbsentFromYAML(stateYAML, converter.ConditionallyIgnoredFields)
		equivalent, err := converter.ResourceYAMLEquivalent(stateYAML, apiResponseYAML, additionalIgnored, []string{converter.AnnotationSharing})
		if err != nil {
			resp.Diagnostics.AddWarning(
				"Check Rule Comparison Error",
				fmt.Sprintf("Error comparing check rules: %s. Using API response as source of truth.", err),
			)
			state.CheckRuleYaml = types.StringValue(apiResponseYAML)
		} else if !equivalent {
			tflog.Debug(ctx, "Check rule has changed, updating state")
			state.CheckRuleYaml = types.StringValue(apiResponseYAML)
		} else {
			tflog.Debug(ctx, "Check rule is equivalent, ignoring changes in metadata fields")
		}
	} else {
		state.CheckRuleYaml = types.StringValue(apiResponseYAML)
	}

	// Set refreshed state
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *CheckRuleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get current state
	var state checkRuleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Retrieve values from plan
	var plan checkRuleModel
	diags = req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate YAML format
	var checkRuleYaml interface{}
	err := yaml.Unmarshal([]byte(plan.CheckRuleYaml.ValueString()), &checkRuleYaml)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid YAML",
			fmt.Sprintf("Check rule definition is not valid YAML: %s", err),
		)
		return
	}

	// Update the existing check rule (dataset changes force recreation via RequiresReplace)
	// Pass YAML directly to client (the client handles Prometheus->Dash0 conversion)
	plan.Origin = state.Origin
	// The check rule's identifier is immutable, so neither the id nor the URL
	// change on update; carry them from state instead of re-resolving them via
	// the API.
	plan.ID = state.ID
	plan.URL = state.URL
	err = r.client.UpdateCheckRule(ctx, plan.Origin.ValueString(), plan.CheckRuleYaml.ValueString(), plan.Dataset.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update check rule, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "updated a check rule resource")

	// Set state to fully populated data
	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

func (r *CheckRuleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state checkRuleModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteCheckRule(ctx, state.Origin.ValueString(), state.Dataset.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete check rule, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "deleted a check rule resource")
}

// ImportState function is required for resources that support import
func (r *CheckRuleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	idParts := strings.Split(req.ID, ",")
	if len(idParts) != 2 {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID in the format 'dataset,origin'. Got: %s", req.ID),
		)
		return
	}

	dataset := idParts[0]
	origin := idParts[1]

	apiResponseYAML, err := r.client.GetCheckRule(ctx, origin, dataset)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Importing Check Rule",
			fmt.Sprintf("Could not get check rule with origin=%s, dataset=%s: %s", origin, dataset, err),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("origin"), origin)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("dataset"), dataset)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("check_rule_yaml"), apiResponseYAML)...)

	// Resolve the id and web app URL (best-effort).
	model := checkRuleModel{Origin: types.StringValue(origin), Dataset: types.StringValue(dataset)}
	r.resolveCheckRule(ctx, &model, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), model.ID)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("url"), model.URL)...)
}

// injectMetadataName copies metadata.name from sourceYAML into targetYAML when
// it is present in the source but absent from the target. This compensates for
// the Dash0 API not preserving the CRD metadata name in check rules.
func injectMetadataName(sourceYAML, targetYAML string) string {
	var source, target map[string]interface{}
	if yaml.Unmarshal([]byte(sourceYAML), &source) != nil {
		return targetYAML
	}

	sourceMeta, _ := source["metadata"].(map[string]interface{})
	if sourceMeta == nil {
		return targetYAML
	}
	name, ok := sourceMeta["name"]
	if !ok || name == nil {
		return targetYAML
	}

	if yaml.Unmarshal([]byte(targetYAML), &target) != nil {
		return targetYAML
	}
	targetMeta, _ := target["metadata"].(map[string]interface{})
	if targetMeta == nil {
		targetMeta = make(map[string]interface{})
		target["metadata"] = targetMeta
	}
	if _, exists := targetMeta["name"]; !exists {
		targetMeta["name"] = name
		out, err := yaml.Marshal(target)
		if err != nil {
			return targetYAML
		}
		return string(out)
	}
	return targetYAML
}
