package provider

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"github.com/dash0hq/terraform-provider-dash0/internal/converter"
	"github.com/dash0hq/terraform-provider-dash0/internal/provider/client"
	customplanmodifier "github.com/dash0hq/terraform-provider-dash0/internal/provider/planmodifier"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"gopkg.in/yaml.v3"
)

// teamAlwaysIgnoredFields lists YAML paths that are always stripped during
// drift detection. The server surfaces these on read but they are not part of
// the user's declarative intent — they are either fully server-generated
// (apiVersion, dash0.com/{id,source,created-at,updated-at}) or already
// captured elsewhere in state (dash0.com/origin, which is stored as the
// dedicated origin attribute). Stripping them here means the read-side
// comparison against `team_yaml` sees only the fields the user authored.
var teamAlwaysIgnoredFields = []string{
	"metadata.labels.dash0.com/id",
	"metadata.labels.dash0.com/origin",
	"metadata.labels.dash0.com/source",
	"metadata.annotations.dash0.com/created-at",
	"metadata.annotations.dash0.com/updated-at",
}

// Ensure the implementation satisfies the expected interfaces.
var (
	_ resource.Resource                = &TeamResource{}
	_ resource.ResourceWithConfigure   = &TeamResource{}
	_ resource.ResourceWithImportState = &TeamResource{}
)

// NewTeamResource is a helper function to simplify the provider implementation.
func NewTeamResource() resource.Resource {
	return &TeamResource{}
}

// TeamResource is the resource implementation.
type TeamResource struct {
	client client.Client
}

// teamModel is the Terraform state model for a team resource.
type teamModel struct {
	Origin   types.String `tfsdk:"origin"`
	ID       types.String `tfsdk:"id"`
	TeamYaml types.String `tfsdk:"team_yaml"`
}

// Configure adds the provider configured client to the resource.
func (r *TeamResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *TeamResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_team"
}

func (r *TeamResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a Dash0 Team. Teams group organization members so alert notifications, dashboards, and other assets " +
			"can be attributed to a shared owner. Teams are organization-level resources and are not scoped to a dataset.\n\n" +
			"Membership in `spec.members` accepts either the member's email address or their internal Dash0 id (the " +
			"`dash0.com/id` label value returned by the Members API, e.g. `user_01ABC...`). Emails are matched " +
			"case-insensitively and translated to internal ids during reconciliation on the server. The provider normalizes " +
			"server responses back to email addresses for legibility, so writing emails and refreshing state produces no drift.",

		Attributes: map[string]schema.Attribute{
			"origin": schema.StringAttribute{
				Description: "A unique identifier for the team, automatically generated by the provider on creation. " +
					"Used to reference the team for updates, reads, deletes, and imports.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"id": schema.StringAttribute{
				Description: "The server-assigned UUID of the team, resolved by the provider after creation. Reference this " +
					"value from other resources that need the raw team id.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"team_yaml": schema.StringAttribute{
				Description: "The team definition in YAML format, following the `Dash0Team` CRD envelope (`kind: Dash0Team`, " +
					"`metadata.name` for the technical name, and `spec.display` plus `spec.members` for the human-facing " +
					"attributes and membership). Server-managed metadata fields (`dash0.com/id`, `dash0.com/source`, " +
					"`dash0.com/created-at`, `dash0.com/updated-at`) are stripped from the state on read; the provider stamps " +
					"`dash0.com/origin` from the `origin` attribute on write.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					customplanmodifier.YAMLSemanticEqualWith(teamAlwaysIgnoredFields),
				},
			},
		},
	}
}

// resolveTeamID populates the team's server-assigned id on the model by
// looking it up via the get endpoint. Failures are surfaced as warnings and
// leave the attribute null rather than failing the operation, mirroring the
// convention established by other resources.
func (r *TeamResource) resolveTeamID(ctx context.Context, model *teamModel, diags *diag.Diagnostics) {
	id, err := r.client.ResolveTeam(ctx, model.Origin.ValueString())
	if err != nil {
		diags.AddWarning(
			"Unable to resolve team id",
			fmt.Sprintf("The team was saved successfully, but its id could not be determined: %s", err),
		)
		model.ID = types.StringNull()
		return
	}
	model.ID = stringOrNull(id)
}

func (r *TeamResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var model teamModel
	diags := req.Plan.Get(ctx, &model)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Generate a provider-owned origin with the tf_ prefix. The origin must
	// not contain slashes because the API client sends it verbatim as a URL
	// path segment; UUIDs with dashes satisfy that constraint.
	model.Origin = types.StringValue("tf_" + uuid.New().String())

	// Validate YAML format before conversion.
	var parsed interface{}
	err := yaml.Unmarshal([]byte(model.TeamYaml.ValueString()), &parsed)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid YAML",
			fmt.Sprintf("Team definition is not valid YAML: %s", err),
		)
		return
	}

	// Convert YAML to JSON for the API client.
	jsonBody, err := converter.ConvertYAMLToJSON(model.TeamYaml.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Conversion Error", fmt.Sprintf("Unable to convert team YAML to JSON: %s", err))
		return
	}

	err = r.client.CreateTeam(ctx, model.Origin.ValueString(), jsonBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create team, got error: %s", err))
		return
	}

	// Resolve the server-assigned id for the newly created team (best-effort).
	r.resolveTeamID(ctx, &model, &resp.Diagnostics)

	tflog.Trace(ctx, "created a team resource")

	// Set state to fully populated data.
	diags = resp.State.Set(ctx, model)
	resp.Diagnostics.Append(diags...)
}

func (r *TeamResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// Get current state.
	var state teamModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	apiResponseJSON, err := r.client.GetTeam(ctx, state.Origin.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read team, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "read a team resource")

	// Compare current state against the retrieved team so drift is detected
	// only on fields the user actually authored. teamAlwaysIgnoredFields
	// strips server-managed labels/annotations that the read path retains
	// for provenance but that the user does not manage.
	if state.TeamYaml.ValueString() != "" {
		stateYAML := state.TeamYaml.ValueString()
		additionalIgnored := converter.FieldsAbsentFromYAML(stateYAML, converter.ConditionallyIgnoredFields)
		additionalIgnored = append(additionalIgnored, teamAlwaysIgnoredFields...)
		equivalent, err := converter.ResourceYAMLEquivalent(stateYAML, apiResponseJSON, additionalIgnored, nil)
		if err != nil {
			resp.Diagnostics.AddWarning(
				"Team Comparison Error",
				fmt.Sprintf("Error comparing teams: %s. Using API response as source of truth.", err),
			)
			state.TeamYaml = types.StringValue(apiResponseJSON)
		} else if !equivalent {
			tflog.Debug(ctx, "Team has changed, updating state")
			state.TeamYaml = types.StringValue(apiResponseJSON)
		} else {
			tflog.Debug(ctx, "Team is equivalent, ignoring changes in server-managed fields")
		}
	} else {
		state.TeamYaml = types.StringValue(apiResponseJSON)
	}

	// Set refreshed state.
	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
}

func (r *TeamResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// Get current state to preserve the origin (immutable across updates)
	// and the previously resolved id.
	var state teamModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Retrieve values from plan.
	var plan teamModel
	diags = req.Plan.Get(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Validate YAML format.
	var parsed interface{}
	err := yaml.Unmarshal([]byte(plan.TeamYaml.ValueString()), &parsed)
	if err != nil {
		resp.Diagnostics.AddError(
			"Invalid YAML",
			fmt.Sprintf("Team definition is not valid YAML: %s", err),
		)
		return
	}

	jsonBody, err := converter.ConvertYAMLToJSON(plan.TeamYaml.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Conversion Error", fmt.Sprintf("Unable to convert team YAML to JSON: %s", err))
		return
	}

	// Carry the origin and id from state — origin is immutable after create,
	// and the team's server-assigned id does not change on update.
	plan.Origin = state.Origin
	plan.ID = state.ID
	err = r.client.UpdateTeam(ctx, plan.Origin.ValueString(), jsonBody)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update team, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "updated a team resource")

	diags = resp.State.Set(ctx, plan)
	resp.Diagnostics.Append(diags...)
}

func (r *TeamResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state teamModel
	diags := req.State.Get(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteTeam(ctx, state.Origin.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete team, got error: %s", err))
		return
	}

	tflog.Trace(ctx, "deleted a team resource")
}

// ImportState allows importing an existing team by its origin (or the raw
// team id — the server-side endpoint accepts either).
func (r *TeamResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	origin := req.ID

	apiResponseJSON, err := r.client.GetTeam(ctx, origin)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Importing Team",
			fmt.Sprintf("Could not get team with origin=%s: %s", origin, err),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("origin"), origin)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("team_yaml"), apiResponseJSON)...)

	// Resolve the id (best-effort).
	model := teamModel{Origin: types.StringValue(origin)}
	r.resolveTeamID(ctx, &model, &resp.Diagnostics)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), model.ID)...)
}
