name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: './go.mod'

      - name: Set up Terraform CLI
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_wrapper: false

      - name: Linting
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.9
          install-mode: goinstall

      - name: Build & Test
        run: |
          make build
          make testacc
        env:
          DASH0_URL: ${{ secrets.DASH0_URL }}
          DASH0_AUTH_TOKEN: ${{ secrets.DASH0_AUTH_TOKEN }}

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: './go.mod'

      - name: Install golangci-lint
        run: make lint-go-install

      - name: Run golangci-lint
        run: make lint-go

  lint-sh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run ShellCheck
        run: make lint-sh
